modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/Tagnum-Mods/ChickensMod/issues"

[[mods]]
modId="chickens"
version="${file.jarVersion}"
displayName="Chickens"
credits="Thanks for this example mod goes to Java"
authors="SetyCz, Wyvi, TagnumElite"
description='''
Chickens... lots of chickens.
'''

[[dependencies.chickens]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chickens]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
